#!/bin/sh

REPO_DIR=/root/$GITHUB_REPO


cd /root
[ -f /secrets/id_rsa ] && cp /secrets/id_rsa /root/.ssh && chmod 600 /root/.ssh/id_rsa

KNOWNHOST=0
if [ -f /root/.ssh/known_hosts ]; then
    KNOWNHOST=$(cat /root/.ssh/known_hosts | grep ^github.com | wc -l | tr -d "[:blank:]")
fi

if [ $KNOWNHOST == 0 ]; then
    ssh -T -o "StrictHostKeyChecking no" git@github.com
fi

git config --global user.email "yeolhyun.kwon@gmail.com"
git config --global user.name "Yeolhyun Kwon"

if [ -d $REPO_DIR ]; then
    cd $REPO_DIR
    git pull
else
    cd /root
    git clone git@github.com:$GITHUB_USER/$GITHUB_REPO
fi

cd /script

if [ -f /secrets/cred.json ]; then
    python downloader.py /secrets/cred.json
else
    echo "/secrets/cred.json DOES NOT exist."
fi

for file in *.enc
do
    newfilename=$(echo $file | sed 's/IndexData_\(.*\).zip.enc/\1/g')
    if [ ! -e $REPO_DIR/$newfilename.enc ]; then
        mv $file $REPO_DIR/$newfilename.enc
        cd $REPO_DIR
        git add $newfilename.enc
        git commit -a -m "$newfilename"
        git push
        cd /script
    fi
done
